# Generated by Django 5.0.4 on 2025-11-03 13:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50, unique=True, verbose_name='Tên thể loại')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Thể loại',
                'verbose_name_plural': 'Thể loại',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('chapter_id', models.AutoField(primary_key=True, serialize=False)),
                ('chapter_number', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Số chương')),
                ('title', models.CharField(max_length=255, verbose_name='Tên chương')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Nội dung chữ')),
                ('image_urls', models.JSONField(blank=True, default=list, null=True, verbose_name='Danh sách ảnh')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian xuất bản')),
            ],
            options={
                'verbose_name': 'Chương truyện',
                'verbose_name_plural': 'Chương truyện',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('story_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Tên truyện')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tác giả')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tóm tắt')),
                ('upload_image_temp', models.ImageField(blank=True, null=True, upload_to='temp_uploads/', verbose_name='Chọn file ảnh để tải lên')),
                ('cover_image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Ảnh bìa Cloudinary')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('status', models.CharField(choices=[('ongoing', 'Đang tiến hành'), ('completed', 'Hoàn thành'), ('paused', 'Tạm ngưng')], default='ongoing', max_length=20, verbose_name='Trạng thái')),
                ('views_count', models.BigIntegerField(default=0, verbose_name='Lượt xem')),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Đánh giá TB')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian đăng')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian cập nhật')),
                ('categories', models.ManyToManyField(related_name='stories', to='story.category')),
            ],
            options={
                'verbose_name': 'Truyện',
                'verbose_name_plural': 'Truyện',
                'db_table': 'stories',
            },
        ),
        migrations.CreateModel(
            name='ReadingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Lần đọc cuối')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='story.chapter', verbose_name='Chương đã đọc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='story.story', verbose_name='Truyện')),
            ],
            options={
                'verbose_name': 'Lịch sử đọc',
                'verbose_name_plural': 'Lịch sử đọc',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Điểm đánh giá (1-5)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian đánh giá')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='story.story', verbose_name='Truyện')),
            ],
            options={
                'verbose_name': 'Đánh giá',
                'verbose_name_plural': 'Đánh giá',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nội dung bình luận')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian bình luận')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Đã được duyệt')),
                ('ai_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Điểm AI phản cảm')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='story.comment', verbose_name='Bình luận cha')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='story.story', verbose_name='Truyện')),
            ],
            options={
                'verbose_name': 'Bình luận',
                'verbose_name_plural': 'Bình luận',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='story.story', verbose_name='Truyện'),
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Thời gian thêm')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='story.story', verbose_name='Truyện')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Truyện yêu thích',
                'verbose_name_plural': 'Truyện yêu thích',
            },
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['title'], name='stories_title_28645b_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['author'], name='stories_author_8522c9_idx'),
        ),
        migrations.AddIndex(
            model_name='readinghistory',
            index=models.Index(fields=['user', '-last_read_at'], name='story_readi_user_id_91de9d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='readinghistory',
            unique_together={('user', 'story')},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('story', 'user')},
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['story', 'is_approved', '-created_at'], name='story_comme_story_i_e9d1e9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('story', 'chapter_number')},
        ),
        migrations.AlterUniqueTogether(
            name='userfavorite',
            unique_together={('user', 'story')},
        ),
    ]
