# Generated by Django 5.2.7 on 2026-02-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='translator',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dịch giả'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['translator'], name='stories_transla_051566_idx'),
        ),
    ]
