# Generated by Django 5.1.5 on 2026-02-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_story_translator_story_stories_transla_051566_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='translator',
            field=models.CharField(blank=True, default='Đang cập nhật', max_length=100, null=True, verbose_name='Dịch giả'),
        ),
    ]
